"""Deterministic reference tables; JSON rules remain canonical."""

from pathlib import Path


def generated_docs(rules):
    town_halls = sorted(int(th) for th in rules["town_halls"])
    header = ["# Home Village catalogue", "", "Generated by `py -3.14 -m coc_base docs`. Edit the canonical JSON, then regenerate.", "",
              f"Snapshot: **{rules['id']}** · verified {rules['verified_on']}. See [sources and conflicts](sources.md) and [inventory rules](rules.md).", "",
              "Counts are unmerged limits. Subtract ingredients consumed by merged defenses. The explicit `--preset max` account command derives inventory from this catalogue and applies those mergers.", "",
              "| Type | Name | Category | Tiles | Unlock TH | Sources |", "| --- | --- | --- | --- | --- | --- |"]
    for kind,spec in sorted(rules["objects"].items()):
        unlock = next((th for th in town_halls if spec["max_levels"][str(th)] and rules["town_halls"][str(th)]["limits"].get(kind,0)), "optional")
        header.append(f"| {kind} | {spec['name']} | {spec['category']} | {spec['width']}×{spec['height']} | {unlock} | {', '.join(spec['sources'])} |")
    header += ["", "## Counts and maximum levels", "", "Every cell is `unmerged count / maximum ordinary level`. Zero count means unavailable even if its underlying asset has an earlier level prerequisite. Supercharges, hero/pet/troop levels and combat statistics are outside geometric validation.", ""]
    for offset in range(0,len(town_halls),9):
        group = town_halls[offset:offset+9]
        header += [f"### TH{group[0]}–{group[-1]}", "", "| Type | " + " | ".join(f"TH{th}" for th in group) + " |", "| --- | " + " | ".join("---" for _ in group) + " |"]
        for kind,spec in sorted(rules["objects"].items()):
            header.append("| " + kind + " | " + " | ".join(f"{rules['town_halls'][str(th)]['limits'].get(kind,0)}/{spec['max_levels'][str(th)]}" for th in group) + " |")
        header.append("")
    header += ["## Merger recipes", "", "| Result | Consumed objects | Minimum consumed level | Gear-up required |", "| --- | --- | --- | --- |"]
    for kind,recipe in rules["mergers"].items():
        header.append(f"| {kind} | {', '.join(f'{v} {k}' for k,v in recipe['consumes'].items())} | {recipe['ingredient_level']} | {recipe.get('geared', False)} |")
    header += ["", "## Account and setting prerequisites", "",
               "Purchased huts and B.O.B. depend on the actual account. Developed profiles include every non-optional inventory slot; they do not require every optional purchase or external unlock.", ""]
    for kind,spec in sorted(rules["objects"].items()):
        if spec.get("notes"):
            header.append(f"- **{kind}**: {spec['notes']}")
        for key,values in spec.get("setting_min_levels",{}).items():
            header.append(f"- **{kind}.{key}**: " + "; ".join(f"{value} requires object level {level}" for value,level in values.items()) + ".")
    phase = rules["crafted_phase"]
    header += ["", "## Crafted Defense snapshot", "", f"Phase `{phase['id']}`: {', '.join(phase['variants'])}. One {rules['objects']['crafting_station']['width']}×{rules['objects']['crafting_station']['height']} slot, available from TH{phase['min_th']}. Three module levels use 0-based values; 0 is the free initial module, 9 is the fully upgraded module at TH18.", "",
               "| TH | Maximum module level |", "| --- | --- |"]
    header += [f"| {th} | {cap} |" for th,cap in phase["module_max_levels"].items()]
    return "\n".join(header) + "\n"


def write_docs(rules, destination):
    destination = Path(destination)
    destination.mkdir(parents=True, exist_ok=True)
    (destination/"catalogue.md").write_text(generated_docs(rules), encoding="utf-8")
